### ISSUE TITLE
Install requirements_c.txt also in .travis.yml

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#19]
@brianhelba should we also be installing [requirements_c.txt](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/requirements_c.txt) in .travis.yml.

I had to separate all packages that depend on c libraries into a separate file for ReadTheDocs to work. The issue is described [here](http://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules). I had to [add mocks for them](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/docs/conf.py#L51) in docs/conf.py and [exclude them from install_requires](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/setup.py#L34) in setup.py to get the documentation to build without failure on ReadTheDocs. Dont know if there is a better way?

**Comment by cdeepakroy** [comment]
@jbeezley On a related note, I have been looking for an answer to [this](http://stackoverflow.com/questions/35802939/install-only-available-packages-using-conda-install-yes-file-requirements-t) question i posted on stackoverflow for a while. I asked zach and he said you would be a good person to ask.

Is there a workaround for this?

The only solution i can think of is to split the requirements.txt into two files requirements_conda.txt (contains packages available on conda) and requirements_pypi.txt (contains packages not on conda but on pypi). Then i can run the following two commands in sequence:

```
conda install --yes --file requirements_conda.txt
pip install -r requirements_pypi.txt
```

I faced this problem in HistomicsTK. In [requirements_c.txt](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/requirements_c.txt#L6), the package nimfa is there on pypi but not on conda. So if i try to install it using conda [here](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/.travis.yml) in .travis.yml the command fails because the package nimfa is not on conda.

I tried to build nimfa for conda by creating a recipe using 

```
conda skeleton pypi nimfa
conda build nimfa
conda convert <nimfa-built-package-file> -p all
```

But `conda build nimfa` fails with a wierd error saying "ValueError: bad marshal data (unknown type code)".

In such scenarios if conda falls back to pip for packages that are not on conda it would solve problems like this.

Any ideas?

**Comment by jbeezley** [comment]
I haven't really used conda before, so I can't say for sure what the best practices are.  I think conda is one of the things that you are supposed to buy into completely.  If you use it at all, you should use it for everything.  In this case, that would mean fixing the nimfa build for conda.  The problem appears to be that the nimfa package on pypi contains pyc files:

```
./nimfa/datasets/__init__.pyc
./nimfa/datasets/__pycache__/__init__.cpython-34.pyc
```

I was able to get the conda build to complete by replace the skeleton build script with this:
```
#!/bin/bash

rm -f nimfa/datasets/__init__.pyc
rm -fr nimfa/datasets/__pycache__
$PYTHON setup.py install
```

In regards to the readthedocs question, you should **always** list all requirements in `install_requires`.  I would work around RTD by unchecking this this option:
```
Install your project inside a virtualenv using setup.py install
```
then set the requirements file to `docs/requirements.txt`.  In that file, put the deps you want to install on read the docs.  You will have to alter the `sys.path` in `docs/conf.py` as well so that autodoc can find the `histomicstk` module since you are no longer installing it.

**Comment by cdeepakroy** [comment]
@jbeezley Thanks! I can now `conda build nimfa` successfully. Based on your suggestion, from now on i will try as much as possible to install every dependency using conda (conda build it if not available).

I came up with this [code snippet](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/setup.py#L25-L41) in setup.py as a workaround for RTD. If not on RTD, it puts all requirements in install_requires. If on RTD, it excludes the packages depending on c libraries.

**Comment by brianhelba** [comment]
Sorry, I didn't get a chance to chime in here before, so I'm reopening the issue. I should have replied earlier.

I'm a big fan of Conda, but I'd disagree with @jbeezley 's assessment that it's all or nothing. `pip` and `conda` work just fine together. I regularly do installs where I first get the "difficult" packages from Conda, then follow it up with a `pip install -r requirements.txt`, and Pip will only install those packages that weren't already added by Conda. The only challenge would be if the packages are named differently in Pip and Conda, but if that happens, it's probably a sign that something is very wrong with the deployment ecosystem of that package.

So, I'd fully support the original suggestion:
```
conda install --yes --file requirements_conda.txt
pip install -r requirements_pypi.txt
```
The list of abstract requirements in `setup.py` should be the concatenation of `requirements_conda.txt` and `requirements_pypi.txt`, since they both operate in the same package namespace.

I would **not** go about trying to install everything with Conda (nor create your own builds just for the sake of it). That is going to be a long-term maintainability disaster, as the latest upstream released are generally guaranteed to go on PyPi, and most packages are easy to build with Pip. Just use Conda where it's needed (`OpenCV`, `Numpy`, etc.).

Finally, note that as a Python distribution, Miniconda is quite handy, and you can certainly use that as an alternative to vanilla Virtualenv. Its version of Pip works just fine (in theory, you never need to use Conda if you don't want).

**Comment by brianhelba** [comment]
@cdeepakroy So, how do you want to handle `nimfa`? I haven't used this library myself, what exactly is preventing it from being usable from PyPi?

If we simply must install `nimfa` from Conda, are you committed to maintaining that build as upstream releases new versions? Is that something you can reach out to the upstream devs of nimfa to coordinate?

**Comment by cdeepakroy** [comment]
I agree. I did this before we discussed when i thought we must install as much as possible with conda and use pip for the rest.

I just moved nimfa to requirements_c.txt to be installed by pip.
