### ISSUE TITLE
Use overlapping tiles while segmenting nuclei

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#306]
This issue concerns enhancing the NucleiDetection CLIs to use overlapping tiles. This may result in issues such as 
* same nuclei being detected in neighboring overlapping tiles
* nuclei cut by image border in one tile while detected in whole in the neighboring overlapping tile

**Comment by manthey** [comment]
Algorithmically, we could run the segmentation with overlap.  We would add an overlap parameter and have it default to something like a 1/4 tor 1/8 tile size.  If a boundary is too close to an overlapping edge, we should discard it (so that we don't keep partial boundaries) -- maybe this is 1/4 of the overlap size.   Otherwise, when we aggregate boundaries from tiles, we would only keep new boundaries which do not intersect already loaded boundaries.
