### ISSUE TITLE
Easy setup of DSA stack using vagrant

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#40]
@brianhelba can we assign this to someone? This will allow everyone to use the same development environment.

**Comment by brianhelba** [comment]
This will be a part of the https://github.com/DigitalSlideArchive/digital_slide_archive repo. I'll try to add something basic today.

**Comment by cdeepakroy** [comment]
@brianhelba Ok. Also, can we base it out of ubuntu 16.04 so we can simply do [`apt-get install insight-toolkit4-python`](http://packages.ubuntu.com/search?keywords=insighttoolkit4-python) and get ITK with python wrapping.

**Comment by brianhelba** [comment]
+1 To using 16.04 eventually, as that will fix a lot of the pain we've had with VIPS / and OpenSlide.

However, 16.04 isn't going to be released for another 2 weeks, and it will be a while before everything gets fully migrated to that (e.g. we have to upgrade our own servers and VMs, Vagrant has to release a new image, Travis needs to support it).

So, I'm starting with support for 14.04 because I can adequately test on that right now, but we can add 16.04 as the various pieces come online.

**Comment by cdeepakroy** [comment]
Ok.

Vagrant already seems to have an image for ubuntu 16.04. See [this](https://vagrantcloud.com/ubuntu).

According to [this](https://github.com/travis-ci/travis-ci/issues/5659) TravisCI doesnt plan to support 16.04 this year. They seem to suggest a workaround using Docker.
