### ISSUE TITLE
API methodology to copy annotation

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#422]
While there is a simple way to *move* annotations, there is no simple way in the current API to *copy* them from one slide to the other. I had to make a workaround by fetching the annotation json object as a python dict then make a server request. There should be an easier way to do this, in my opinion, just like there is an easy way to copy slides from one directory to another.

`annotation_json = gc.get('/annotation/' + annot_id)`

`# MOVE annotation to copied slide`
`#gc.put("/annotation/{}?itemId={}".format(annot_id, copied_slide_id))`

`# COPY annotation to slide -- This does not work for some reason!!`
`#annotation_json_str = json.dumps(annotation_json['annotation'])`
`#gc.post("/annotation?itemId=" +  copied_slide_id + "&body=" + annotation_json_str)`

`# COPY annotation to destination slide`
`_ = requests.post(url = apiUrl + 'annotation?itemId=' + slide_id, headers = headers, json = annotation_json['annotation'])`

**Comment by jbeezley** [comment]
https://github.com/girder/large_image/pull/229 implements a single endpoint for copying annotations.  The API will look like this:
```
POST /annotation/{id}/copy?itemId={itemId}
```

Just as a comment `gc.post("/annotation?itemId=" + copied_slide_id + "&body=" + annotation_json_str)` won't work because you are adding the annotation content to a url parameter called "body", not the body itself.  For requests, the correct way to add content to the body of a request is with the `json` parameter like you have in the last line.  This works with the girder python client like this:
```
gc.post("/annotation?itemId=" + copied_slide_id, json=annotation_json['annotation'])
```

**Comment by kheffah** [comment]
@jbeezley Got it! Thank you for clarifying how this works and for pointing me to the endpoint that will fix this.

**Comment by manthey** [comment]
Added in https://github.com/girder/large_image/pull/229.
