### ISSUE TITLE
Need ability to define default annotation group styles 

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#427]
It would be very useful to have a set of default annotation styles to choose from, as a way of standardizing data acquisition for projects involving many members. I can provide a list of common styles to set, but it would be even better if the group admins have the ability to define default styles themselves.

**Comment by cooperlab** [comment]
It would be nice if this could be defined in say an XML - and then applied throughout a project to ensure consistent application of class names, colors, etc.

**Comment by kheffah** [comment]
Yes, that's how I also imagine it.

**Comment by manthey** [comment]
We could make this a setting in the HistomicsTK plugin's settings page that would be a json object.

An admin user could set things up in their browser, then we could get a json representation of that and use that string for the value.  The settings could also include "Prevent default groups from being modified" and "Disallow new groups", so that non-admin users couldn't then modify the styles.

**Comment by kheffah** [comment]
Sounds good. I like the flexiblity of having group admins define styles. This ensures that for different projects (eg different tumor type) there's flexibility to work with new styles. Thanks!

**Comment by manthey** [comment]
Added in PR #439.
