### ISSUE TITLE
Create an API for getting tiles of whole-slide images

### ISSUE THREAD

**Issue by cdeepakroy** [DigitalSlideArchive/HistomicsTK#47]
A good way to do this is by creating an abstract `WholeSlideImage` class which defines the API and then make derived classes of it such as `GirderWholeSlideImage` (which serves an image stored on girder) and `LocalWholeSlideImage` (which serves an image located on the local machine). 

We would want all analysis functions in histomicstk to take objects of the abstract `WholeSlideImage` class as input instead of a numpy array or PIL image.

**Comment by brianhelba** [comment]
This is basically an extension of [the ``TileSouce`` classes in ``large_image``](https://github.com/DigitalSlideArchive/large_image/tree/master/server/tilesource), that allows arbitrary regions of an image to be retrieved.

We should keep all I/O code within ``large_image``, and in fact, the ``large_image`` plugin is already independently planning to add support for arbitrary regions to provide enhanced thumbnail capability and support for the FIF HTTP tile protocol.

To move this along, can you give some specific examples of API calls that you need to make against images?

**Comment by cdeepakroy** [comment]
For some exemplary API calls see the following files: [Sample](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/Sample.py), [ReinhardSample](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/ReinhardSample.py), [TilingSchedule](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/TilingSchedule.py).

Yes! We need something like TileSource. We can extend it to support the API calls we end up needing. One thing that concerns me is that as of now large_image is a girder plugin and serves tiles from images on girder. I think we will also need an abstract `TileSource` class which defines the public API. And have derived classes such as `GirderTileSource` for serving tiles from images on girder and `LocalFileSystemTileSource` for serving tiles from images on the local machine. 

Also, maybe we should also extend large_image to behave both as a girder plugin and as a pure python package just like HistomicsTK. And when someone uses large_image just as a pure python package by pip installing it and importing it to their code they should only get access to the abstract `TileSource` class and the `LocalFileSystemTileSource`. And `GirderTileSource` should be defined under the server directory and only be accessible when used as a girder plugin.

**Comment by brianhelba** [comment]
Here's how we get access to the internal Girder API from a third-party Python app:
```
import sys
if '/path/to/girder' not in sys.path:
    sys.path.append('/path/to/girder')
from girder.utility import server as girder_server
girder_server.configureServer()
```
At that point, we could do something like:
```
from girder.utility.model_importer import ModelImporter

def loadImageFromGirderItem(girderItemId):
    item = ModelImporter.model('item').load(girderItemId, force=True)
    imageMetadata = ModelImporter.model('image_item', 'large_image').getMetadata(item)
    imageData = ModelImporter.model('image_item', 'large_image').getRegion(item, ...)
```

I realize now that the `ImageItem` class could probably use some more methods, particularly a convenience wrapper to graph the entire base image (though it will be huge), and a way to get the image data as a raw PIL image, rather than an encoded `bytes` object (though I also see a counter-argument to leaving this functionality at a lower level, in TileSource).

Feel free to consult with @manthey if I'm not around to discuss this more, but let's try to keep the discussion in this issue (and off email).

**Comment by cdeepakroy** [comment]
@brianhelba I have looked through the code for ImageItem, TileSource, GirderTileSource, SVSGirderTileSource, and TiffGirderTileSource. 

I feel it will be very clean, if the functions (see [Sample](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/Sample.py#L93) for example) in HistomicsTK that want to work with a large image should be taking [TileSource](https://github.com/DigitalSlideArchive/large_image/blob/master/server/tilesource/base.py#L49) as input and interact through its API. 

I also feel we should also move the abstract TileSource class from large_image/server to large_image/large_image. And further add LocalTileSource (abstract class), SvsLocalTileSource, TiffLocalTileSource etc to large_image/large_image which serve tiles from a large image on the local file system (outside girder). This isolation of TileSource classes that do not have any girder dependencies will allow us to use large_image both as a pure python package and as a girder plugin. 

Also this will help the developers to write/test their code with large images residing on the local file system (not on girder) via the LocalTileSource class (which internally calls SvsLocalTileSource, TiffLocalTileSource etc). Since LocalTileSource and GirderTileSource confirm-to/derive-from the TileSource class, all functions when written by taking input a TileSource object, they will work irrespective of where the large image is located.

**Comment by brianhelba** [comment]
I fully support removing extra Girder dependencies. I do want to ensure that the typical case of `itemId` -> `imageData` remains easy, but I think the `ImageItem` can provide a lot of that, and it didn't exist when I first wrote the `TileSource` classes.

@manthey Will be good to help with this, but I want to give him time to finish the annotation API first.

**Comment by cooperlab** [comment]
Deepak's point is a really important - we want to de-couple HistomicsTK from Girder where possible. Many HistomicsTK users will be using the package without a DSA instance.

Sent from my iPhone

On Apr 7, 2016, at 5:05 PM, Deepak Roy Chittajallu <notifications@github.com<mailto:notifications@github.com>> wrote:


@brianhelba<https://github.com/brianhelba> I have looked through the code for ImageItem, TileSource, GirderTileSource, SVSGirderTileSource, and TiffGirderTileSource.

I feel it will be very clean, if the functions (see Sample<https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/Sample.py#L93> for example) in HistomicsTK that want to work with a large image should be taking TileSource<https://github.com/DigitalSlideArchive/large_image/blob/master/server/tilesource/base.py#L49> as input and interact through its API.

I also feel we should also move the abstract TileSource class from large_image/server to large_image/large_image. And further add LocalTileSource (abstract class), SvsLocalTileSource, TiffLocalTileSource etc to large_image/large_image which serve tiles from a large image on the local file system (outside girder). This isolation of TileSource classes that do not have any girder dependencies will allow us to use large_image both as a pure python package and as a girder plugin.

Also this will help the developers to write/test their code with large images residing on the local file system (not on girder) via the LocalTileSource class (which internally calls SvsLocalTileSource, TiffLocalTileSource etc). Since LocalTileSource and GirderTileSource confirm-to/derive-from the TileSource class, all functions when written by taking input a TileSource object, they will work irrespective of where the large image is located.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/DigitalSlideArchive/HistomicsTK/issues/47#issuecomment-207088035>

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by cdeepakroy** [comment]
@brianhelba If in your code above `ModelImporter.model('image_item', 'large_image')` returns a `TileSource` object all problems will be solved.

**Comment by cdeepakroy** [comment]
Also i would like the name `LargeImage` instead of `TileSource` but i wudnt push much on that.

**Comment by brianhelba** [comment]
@cdeepakroy That's not how Girder models and the ModelImporter works, unfortunately; they are basically a combination Factory / Visitor pattern. However, the `TileSource` is a more traditional Python class, so you import it directly.

The refactor as described above is something that I've intended from the very beginning. Once the annotation API is ready (allowing others on the team to proceed in parallel), I think we should take it on.

As for the naming, the distinction is intentional. `TileSource` ultimately operates on the tile level, as that's how these images are stored. It's an interface to abstract away the details of dealing with different types of multiresolution images. While it supports image-wide operations, it needs to be transparent about that fact that these types of operations are inefficient. We can also build additional abstraction layers to translate tiles into images, if you want to do more fancy operations. Of course, I'm open to being convinced otherwise on all of this.

**Comment by dgutman** [comment]
I agree with this discussion---  we want to be able to decouple girder and
histomicsTK for many reasons, including testing among many other use cases.

**Comment by brianhelba** [comment]
@dgutman If you mean software regression testing, then I'd actually argue that's where we want the most dependencies on Girder, as it provides a lot of nice testing framework for free.

If you mean prototyping and ease of adoption by other projects, then yes, that's a goal that I've supported from the very beginning. We just need to get time to do it.

**Comment by brianhelba** [comment]
Btw, thank you all @cdeepakroy @cooperlab @dgutman for pushing to generalize this: it's exactly the spirit that will ensure others adopt our work too. Even if I push back on the timeframe, I hope the enthusiasm continues.

**Comment by cdeepakroy** [comment]
@brianhelba can we add the following member function to the ImageItem class that returns an object of the abstract TileSource class? This can then be passed into functions in HistomicsTK core.

```
class ImageItem(Item)
...
  def getTileSource(self, item **kwargs):
      return self._loadTileSource(item, **kwargs)

```

**Comment by cdeepakroy** [comment]
Also once i finish docker CLI execution, i can move the TileSource class from large_image/server to large_image/large_image and create a setup.py if we agree on isolating it.

**Comment by brianhelba** [comment]
@cdeepakroy What's the difference between the proposed `getTileSource` and `_loadTileSource`? Why not just make `_loadTileSource` public?

**Comment by cdeepakroy** [comment]
@brianhelba That will work as well! 

Shall i rename _loadTileSource to getTileSource (i like this name better) and make it public?

**Comment by brianhelba** [comment]
@cdeepakroy Feel free to make a PR, but let's discuss it with @manthey before merging. He has an important stake in `large_image`, so we need to get his input before any major refactor.

The "load" in `loadTileSource` connotes the fact that it's not an accessor method for a contained member value, but rather it fetches an external class. I propose we keep the name, or form a committee to meet biweekly and discuss it further :wink:

**Comment by manthey** [comment]
I'd be happy to do the refactor, but won't get to it until next week or
so.  If someone makes PR before then, I'm happy to review it.

On Thu, Apr 7, 2016 at 6:56 PM, Brian Helba <notifications@github.com>
wrote:

> @cdeepakroy <https://github.com/cdeepakroy> Feel free to make a PR, but
> let's discuss it with @manthey <https://github.com/manthey> before
> merging. He has an important stake in large_image, so we need to get his
> input before any major refactor.
>
> The "load" in loadTileSource connotes the fact that it's not an accessor
> method for a contained member value, but rather it fetches an external
> class. I propose we keep the name, or form a committee to meet biweekly and
> discuss it further [image: :wink:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DigitalSlideArchive/HistomicsTK/issues/47#issuecomment-207128481>
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by manthey** [comment]
I've just made a PR in the large_image repo so that tile sources can be accessed when girder is unavailable.  Note that since girder requires plugin python code to be in the `server` directory, the module structure is still `server.tilesource`.  As a simple example:

```
from server import tilesource

svs = tilesource.SVSFileTileSource('slidefile.svs')
image = svs.getTile(0, 0, 0)
# image is a jpeg
regionImage, regionMimeType = svs.getRegion(width=1000, height=750, encoding='PNG', left=20000, top=5000, regionWidth=10000, regionHeight=7500)
# regionImage is a 1000x750 png that is extracted from the whole slide and is 1/10th the max resolution
```
