### ISSUE TITLE
Cannot start web server at port != 8080

### ISSUE THREAD

**Issue by maor121** [DigitalSlideArchive/HistomicsTK#510]
I followed the [installation manual](https://digitalslidearchive.github.io/HistomicsTK/installation.html), and got to the part:

```
cd HistomicsTK/ansible
python deploy_docker.py start
```

And got an error:

> docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint histomicstk_histomicstk (...): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use")

This is expected as port 8080 is indeed in use. So I tried:
`python deploy_docker.py start --port 9322
`
Which failed with same error, it seems the port is passed into the script, but somehow it still tries to bind to 8080. I tried changing all the .yml files to use port 9322, and rebuilt the docker images using
`python deploy_docker.py start --port 9322 --build
`
But got the same error. Is it possible to run the webserver at port != 8080?

**Comment by maor121** [comment]
Found the bug, but didn't succeed in making a pull request :)

deploy_docker.py, line: 235
`           'ports': [8080],
`
Should be:
`           'ports': [port],
`

Now it works.

**Comment by manthey** [comment]
@maor121 This surprises me, as by default I run with a port != 8080 and a different application running on 8080.

**Comment by manthey** [comment]
If you do `deploy_docker.sh start --port=<port in use>` and then try `deploy_docker.sh start --port=<free port>`, it doesn't work, because the docker is already started with the wrong port.  If you then do `deploy_docker.sh rm` and then `deploy_docker.sh start --port=<free port>`, it should work with the current code.

It would be better if we knew what parameters `start` was called with, and, if they differ from the previous `start`, we automatically did `rm` first, but that may be too tricky.
