### ISSUE TITLE
Opening and/or previewing .mrsx -files produces low quality results

### ISSUE THREAD

**Issue by AnttiKarlsson** [DigitalSlideArchive/HistomicsTK#579]
Hello!
I am in the progress of trying out and implementing this piece of awesome looking software at the Auria biobank in the Turku university hospital. Our scanner produces mirax files, which are basically a .mrsx file + a folder with the same name containing a bunch of .dat files (the actual image data).

When uploading this stuff into DSA (also when opening in HistomicsTK), only the low quality preview image from the .mrsx shows up and is not zoomable. Openslide does support this file format and I've been able to divide these images into tiles for deep learning with various openslide based pipelines. Is there something I'm doing wrong, or should I try to figure out a way of converting these into some other "single file" fileformat?

**Comment by manthey** [comment]
HistomicsTK does support viewing and annotating .mrxs files.  Because of how Girder stores items and files, we need a small patch to openslide to locate the associated directory properly.  The dockers we post and use via the deploy_docker.py script have this patch, but if you install openslide manually, you need to also apply it.

It is easiest to import mrxs files into Girder rather than upload them.  This ensures that the folder/item/file structure is what is expected.
