### ISSUE TITLE
Hosting on PyPI?

### ISSUE THREAD

**Issue by topspinj** [DigitalSlideArchive/HistomicsTK#606]
The installation process of HistomicsTK is cumbersome. Is it possible to host this on PyPI? What is required to do this? I've noticed a [closed issue](https://github.com/DigitalSlideArchive/HistomicsTK/issues/178) that mentions plans to host on PyPI in 2016.

**Comment by cooperlab** [comment]
We are working towards something that is pip installable. The challenge has been some of the libraries that are responsible for reading data from these proprietary whole-slide imaging formats. @manthey and @cdeepakroy can provide more insights into this and where we are in the process.

**Comment by topspinj** [comment]
What are your thoughts on separating HistomicsTK into a Python package and plug-in? I'm randomly seeing errors from `girder`, which I believe is not being used in the Python package component.

**Comment by manthey** [comment]
HistomicsTK depends on [large_image](https://github.com/girder/large_image), which in turn can require libraries which are cumbersome to install.  large_image has a branch which has just been deployed to pypi (see https://pypi.org/project/large-image/); to install from that you still need to install the appropriate libraries on your system (libtiff, libopenslide, libvips).  There are some python wheels for linux to do this, but, as they are complex, haven't been tested enough to put those wheels on pypi.

We have plans to separate the Girder client from the analysis part of HistomicsTK (much as has been done in large_image), so you can easily use it as a toolkit without Girder or as a Girder plugin.

**Comment by topspinj** [comment]
Thanks! Looking forward to the updates 👍

**Comment by topspinj** [comment]
Would it be possible to make the sample images publicly available so that others can try running the tests?

**Comment by manthey** [comment]
The test images are all publicly available here: https://data.kitware.com/#collection/576ad31a8d777f1ecd6702ee

**Comment by dgutman** [comment]
Yeah as the toolkit matures we are realizing splitting the histomictk from
girder is on our roadmap... Just of course takes time.


We also have dockerized versions of histomicstk which we use... We've been
prioritizing getting everything python3 compliant and then will probably
shift efforts to making sure the pip installation is more robust.

**Comment by topspinj** [comment]
@dgutman thanks for the update! Just out of curiosity, which dependencies are not Python 3 compliant?

**Comment by manthey** [comment]
I'll use this issue to discuss reorganizing some of the source code to aid in releasing to pypi.

We can nearly make a pypi package that installs HistomicsTK directly.  To facilitate this, I think we should move all of the cli code to somewhere under the histomicstk directory.  Specifically, I would move

server/docker-entrypoint.sh -> histomicstk/cli/docker-entrypoint.sh
server/slicer_cli_list.json -> histomicstk/cli/slicer_cli_list.json
server/cli_common/utils.py -> histomicstk/cli/utils.py

and, for all of the clis, something like

server/NucleiDetection/NucleiDetection.py -> histomicstk/cli/NucleiDetection/NucleiDetection.py
server/NucleiDetection/NucleiDetection.xml -> histomicstk/cli/NucleiDetection/NucleiDetection.xml

with the creation of appropriate empty __init__.py files in each directory.

This, with a few changes in the setup.py script, would include all of the non-Girder code in one place, so that someone who installs from pypi would be able to do:

```
pip install histomicstk
python -m histomicstk.cli.NucleiDetection.NucleiDetection <appropriate command line parameters>
```

At the moment, if we don't build wheels, we will still have to have an install process like so:
```
pip install large-image[openslide,tiff,pil]
pip install scikit-build 'git+https://github.com/cdeepakroy/ctk-cli'
pip install histomicstk
```
where you would either have to install libtiff and libopenslide or use the unofficial linux wheels for large-image.

@cdeepakroy and @cooperlab I'd appreciate feedback about reorganizing the cli-related files.

**Comment by cdeepakroy** [comment]
I have a few concerns with this:
* ctk_cli is not on PyPI and it has been a hard bargain to even marge our changes to master there. Will this be a blocker to putting HistomicsTK on PyPI if we reorg CLIs into the core histomicstk package.
* The CLIs are a bunch of command-line scripts. Is it good practice to include command-line scripts into the core package that is more of a library?

**Comment by manthey** [comment]
Answering these in the reverse:

Many packages ship with utility scripts.  Some are installed as commands on your system, others are just available as executable modules.  I would say it isn't particularly common, but not rare either.  The virtue of packaging them is that it allows a user to try things out right away without writing code.  I think this virtue is valuable enough to include them (but I'm not committed to it). 

We've discussed separating the toolkit from the interface.  I think that when we do that, these CLIs would still stay with the toolkit.  If we don't do this, then the CLIs should probably move to a different top-level directory (out of `server` -- I would just then move them to `cli` at the root of the repo). 

We have several options regarding ctk_cli: we could make it an optional dependency (if you don't install it, you just can't use the clis), we can create a forked package with a different name; we could monkey patch from the master package; we could include the code within HistomicsTK.

**Comment by topspinj** [comment]
Some modules within HistomicsTK include `large_image` as a dependency. Would you keep `large_image` as a dependency, or refactor the code to not use it? If you plan to keep it, would you also need to include libtiff, libopenslide, libvips to the requirements file?

**Comment by manthey** [comment]
`large_image` will remain as a dependency.  It can already be installed from pypi and specifies requirements of openslide-python and pylibtiff.

There are some provisional wheels that include linux binaries for those which can be installed via `pip install large-image[openslide,tiff,pil] --find-links https://manthey.github.io/large_image_wheels`.  I hope that there will eventually be official wheels with binaries for these, but I sure that will happen after we have a pip installable version of HistomicsTK.  In the meantime, on an ubuntu 18.04 system, for instance, `apt-get install libopenslide-dev libtiff-dev` is enough that you can install from pip without the `--find-links` option (but that requires root permissions to install libraries).

**Comment by dgutman** [comment]
keeping large image is important as long as it's easy to install as it
basically provides an abstraction layer that allows us to deal with as you
may have guessed any large image. I think many if not all of our algorithms
will work on standard Tiff's and png's but since we generally are testing
on large images that don't fit in memory we need some sort of abstraction
layer to provide a tile source.

**Comment by thewtex** [comment]
xref #647

**Comment by manthey** [comment]
HistomicsTK can now be installed from pypi.
