### ISSUE TITLE
Scalable annotation rendering

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsTK#636]
This is a (potentially ignorant) question(s) and a feature/enhancement request(s). There are scalability concerns in the current system, which I think will need to be addressed as we move from displaying nucleus annotations inside relatively small regions of interest (about 1/20th of tissue area) to whole-slide nucleus annotations. **Put in other words, the volume of annotation items (polygons) we need to render is about 20x anything we have so far, so we need to make sure the performance is very smooth with current annotation volume given it can only go worse as we massively scale up the number of annotations.** To make the formulation of this request more well-defined, **I've recorded my browser (Chrome), including the debug panel**, as I walk through a slide with a moderate number of annotations. The video of the recording can be accessed in this link:

** https://youtu.be/YbPD7OSjQoQ **

**`00:13`** - I click on the 'eye' icon to show all annotation polygons in the slide. It takes up to `00:30` (about 20 seconds) to load all polygons. Not sure if this is good enough or can be improved. The more important issue, however, is the loading behavior. **A server request is made for each annotation document (group of polygons) and as soon as the entire document is loaded, it gets rendered. This is related to issue #625 .** The fact that a huge annotation document needs to be loaded (i.e. our 'unit' is the annotation document not the individual polygon) means a rather large file is loaded before any of the, say, 1000+ polygons is displayed. While all these documents are loading, the page is almost always unresponsive (naturally). The following can be done to address this:
1- As we address issue #625 , we may decide to make the individual polygon (element) as our unit of interest and render each polygon after it is received. _Advantage_: makes more sense. _Disadvantage_: not sure if making 30,000 server requests (one per polygon) makes sense or is efficient. 
2- Alternatively, we may decide to bundle together polygons (say, 1000 elements at a time) automatically when they are requested. This makes sure there is a maximum number of polygons per "bundle" and ensure the wait time before something renders on the screen is reasonable. 
3- Regardless of how we handle this, **a 'loading' bar is needed** to show loading progress like: 

> [=== >                 ] annotation 5 of 10,000

 Not only is this good from a user experience perspective, it also prevents the user from trying to zoom in on their area of interest before all annotations have completely loaded (hence preventing crashing or unresponsiveness). This was suggested in issue #592 .

**`00:31 - 1:43`** - I inspect a few of the server requests made to get annotation documents. Nothing out of the ordinary. Of notice, however, is that this is the only time these requests appear. **In other words, as I pan to different area of the slide afterwards we do not re-fetch any annotations from the server anymore but use the ones already fetched at the start.** That's not necessarily a bad thing, as server requests take time and impact performance. BUT, this implies that one of two things is happening:

1- Either the annotations are rendered once (like a canvas) and that's it. --> _Scalable??_
2- Or, they are stored locally in the browser cache or some local database o the client side and get fetched a few at a time as I pan different areas of the slide. --> _Scalable_

 Which of these two scenarios is happening? From all I could find, it seemed scenario no. 1 is happening which may not be very scalable (I could be wrong about this though).

**`1:44 - 3:22`** - I pan various areas of the slide. There are a bunch of server requests for tiles (images) but none for annotations. 

**`3:23 - 4:20`** - I check local database and browser cache. The only thing that is stored, it seems, are the annotation styles. This seems to confirm scenario no. 1 where the annotations are only rendered once like a canvas. 

Sorry for really long question/request, but I anticipate (and @cooperlab seemed to agree) that these issues will only get magnified as we scale up annotation efforts.

**Comment by manthey** [comment]
Depending on the size of an annotation, either of scenario 1 and 2 are used.

Currently, when you view an annotation, we make a request for that annotation.  If you click the 'view all', we make one request for each annotation, all basically at the same time.  As the annotations are returned, we render what has come back.  Each of these initial queries has a "detail limit" (crudely speaking, this the maximum number of vertices that will be returned -- so polygons are more details than rectangles are more details than points).  If the annotation has less than the detail limit, we have loaded all of it and then display it all without any need to update.  Assuming you have webgl, the system should be tolerably responsive with all of these loaded.

If an annotation exceeds the detail limit, we ask for only the elements within the window that is viewed plus some surrounding area, getting the largest annotation elements by preference if we can't load them all.  Then, when you pan or zoom beyond some near location, we requery to get the elements in that area.  This behavior allows scaling to an annotation that has millions of polygons, since we'll never have the millions in browser memory all at once.

There are several pinch points where things take time: it takes time to make the server query to get the annotations, it takes time to send that information across the network, it takes time to convert the received information into a form we can render, and it takes time to render the annotations.

If we requested less data initially, the responses are faster, the rendering is faster, but the rendering is less complete.

Currently, we transmit data in json; if we used something like a protobuf, we could halve the network traffic volume.  I have an internal hacky branch to try this out -- the network delay is reduced, but my hack makes the server take longer to produce the result (which it wouldn't need to do).  

When there are too many annotations to render all at once, we could send, for instance, just the centroids of the polygons and render them as dots until you zoom in.  On large nuclei sets, the time to send these centroids is still too slow to feel peformant, so this wouldn't be sufficient unto itself.

We could use web workers for the data reception, which would keep things feeling more performant, allowing us to fetch chunks of data and assemble it in the background, then push it to the foreground.  This actually uses more memory (since the worker gets a partial response that then has to be combined with the collected response), so this may reduce the maximum data we want to send to a browser.  However, if done well it could make things feel more responsive.

We could precompute some decimated results for large annotation sets, so that we fetch those subsets initially (simplified polygons at low resolution, for instance, or some sort of heatmap).  This requires more database bookkeeping and more complexity in the rendering client, but could feel more responsive.  This would be added if we used something like PostGIS to store the annotations rather than Mongo, since we could then have an optimized database module do the decimation.

Our default detail limit was picked arbitrarily and is not optimal (and may not be balanced between different element types such as polygons versus rectangles).

**Comment by manthey** [comment]
I should add, there are other places that can be changed to possibly speed things up as well.  Currently each annotation is sent to webgl in a separate buffer.  This is fine for a few annotations with lots of elements, but sub-optimal for many annotations with a medium number of elements.  We reformat the annotations between their transmission format and a display format; this could certainly be improved.

**Comment by kheffah** [comment]
@manthey Thank you for such a detailed and nice response. I agree that these would all be nice to improve performance, and my opinion is to incorporate as many of these as possible since we’ll definitely scale up the number of annotations that need rendering. 
  - Showing centroids is a great idea, especially for polygons that are too small to show at a magnification anyway. We could set a limit that links the size of polygon to the magnification at which it is rendered as a boundary.
  - The current distinction between an annotation with many elements and many annotations with a few elements will eventually be revised anyways as we address the annotation styles CS documents issue.
  - Regardless of how we handle this, the user should be blocked from sending any requests when they click the eye icon to show all annotations. Loading bar should be sufficient for this.
  - Definitely agree that the detail limit would need to be set more rationally, perhaps as a function of type of elements.
  - Related to the annotation document va style issue, it maybe more sensible to make a document for each annotations within a geographic area (eg groups of tiles), regardless of style. The idea being that if there are millions of elements, this gets just one query as you pan to a certain area. Current organization as I understand it would be less efficient for annotations that have thousands of elements geographically scattered in different areas of the slide.
  - Usinng protobuff or other efficiency enhancements would definitely help.
Thanks!

**Comment by manthey** [comment]
As we now send centroids on large annotation collections and fixed an issue when saving changes in quick succession, I'm closing this issue.  Any remaining details should made into new issues.
