### ISSUE TITLE
cannot install HistomicsTK as there is no requirements.txt in the folder

### ISSUE THREAD

**Issue by satotty** [DigitalSlideArchive/HistomicsTK#705]
when I try to install HistomicsTK following the steps as follows and execute '$ pip install --no-cache-dir -r requirements.txt' , an error comes up saying:
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

i also checked the HistomicsTK file but there is no such file: 'requirements.txt'

Once large_image is installed as a python package, HistomicsTK can be installed as follows:

$ git clone https://github.com/DigitalSlideArchive/HistomicsTK.git
$ cd HistomicsTK
$ pip install git+https://github.com/cdeepakroy/ctk-cli
$ pip install --no-cache-dir -r requirements.txt
$ pip install -e .

**Comment by kheffah** [comment]
@satotty Sorry that's documentation that's a bit outdated. Here's what you need to do. 

**To install HistomicsTK using PyPI** :

```bash
$ pip install histomicstk
```

**To install HistomicsTK from source**:

```bash
$ git clone https://github.com/DigitalSlideArchive/HistomicsTK/
$ cd HistomicsTK/
$ python -m pip install scikit-build ninja cython numpy nimfa
$ python setup.py develop
```
The third line is there because there are some issues in the setup.py file that sometimes prevent the installation of some of these libraries, at least in my experience. 

@manthey Should I update the installation instructions accordingly?
