### ISSUE TITLE
[Bug?] *.scn images are not being displayed properly recently

### ISSUE THREAD

**Issue by kavehtp** [DigitalSlideArchive/HistomicsTK#758]
We used to work with *.scn images without any issues using HistomicsTK viewer. However, after a recent update, these images are not being shown properly. Particularly, when there are multiple regions in the slide (see attached), only one of the regions is being displayed. This also causes the analysis algorithms to receive the wrong coordinates for analysis. I am not sure if this is a HistomicsTK problem or large_image issue. Would you please have a look at it? Thanks!
![screenshot](https://user-images.githubusercontent.com/18053246/68756023-6a594700-0644-11ea-9e44-ff92b25ae59a.png)

**Comment by manthey** [comment]
To the best of my knowledge, large_image has only every shown a single region of an SCN file.  In the past, we may have shown a low-resolution overview image rather than a high-resolution region.  Eventually, we'll adding support for showing all regions properly, but I'm not sure when we'll get to that.

**Comment by kavehtp** [comment]
This is interesting because we were using the viewer just fine for all of our SCN files (showing all regions perfectly at highest resolution) and this issue is a very recent event. I thought this might be a side effect of some of the latest changes or the downstream libraries. Thanks anyways.

**Comment by manthey** [comment]
Do you have an SCN file that you know worked properly before that you can share?

**Comment by manthey** [comment]
This was caused by upgrading libtiff from 4.0.9 to 4.1.0.  Although this should have been a non-breaking change, the openslide library is doing *something* differently between those versions of libtiff.  For now, I'll rebuild the large_image_wheels with liibtiff 4.0.9.  There will probably be an update for the HistomicsTK docker files tomorrow or so.

**Comment by manthey** [comment]
I believe this is resolved.  If not, please reopen in the large_image or HistomicsUI repository.
