### ISSUE TITLE
Serving slides from S3 is very slow

### ISSUE THREAD

**Issue by kavehtp** [DigitalSlideArchive/HistomicsTK#759]
Hi. I have been trying to host slides on S3 (through Girder's S3 assetstore) and it appears that HistomicsTK can load WSIs from S3. However, the speed is very low and loading tiles sometimes takes more than 10-15 seconds. Is this expected? Is there a particular setup that I need to follow to speedup S3 queries?

**Comment by manthey** [comment]
Some S3 storage is faster than others.

For instance, I can connect to Google storage via the S3 compatible api.  This is slow; the first tile often takes 10s and subsequent tiles takes from 40 ms to 4 s.  The initial slow speed is purely the time it takes to fetch bytes from the bucket.

However, the same exact file when stored in my own S3 bucket takes less than a second to get the first tile.

I'm not knowledgeable enough in S3 setup to know what configurations are best.

**Comment by dgutman** [comment]
What regions are the s3 bucket and server in? If they are not the same..
that's the first issue

**Comment by kavehtp** [comment]
Thank you both. In my case, some tiles take a few milliseconds while others can take more than 15 seconds. Both server and S3 bucket are in Singapore.

**Comment by kavehtp** [comment]
Is Girder using [S3 Select](https://aws.amazon.com/blogs/aws/s3-glacier-select) for partial retrieval of objects from S3 or does it mount S3 bucket and then accesses the objects as files? I was wondering using S3 Select could potentially improve the performance significantly, particularly for WSI objects. Thanks!

**Comment by manthey** [comment]
Girder accesses S3 objects as files, but does range-requests for them as needed.  When accessing S3 objects as large_image tile sources, the request is sent through the girder-mount Fuse.  By default, linux will buffer reads -- rather than making one request per read, a request is made that reads a larger block of data, then that data is served from memory if the requested area is available.

I've looked at the network traffic for pyramidal tiff files as generated by vips; for those, the requests end up being fairly efficient in terms of a low number of requests and total bytes transferred.  Other formats are probably much less efficient.

It might be worth seeing if using fadvise would improve access times.

**Comment by kavehtp** [comment]
AWS recommended us to implement S3 Select as it appears to be the most efficient way of retrieving part of objects from S3. They also advised against FUSE. Are there any plans to extend Girder to use S3 Select? I guess that would cause some issues because other providers like GCP still don't have an equivalent.

**Comment by manthey** [comment]
There aren't currently plans to use S3 Select.  None of our funded projects currently require faster S3 access than what they have.  Targeted funding or PRs are always welcome -- it shouldn't be too much work to do it.

**Comment by kavehtp** [comment]
Thanks. We will try to implement it and make a PR. Would you please give us some pointers to start?

**Comment by manthey** [comment]
I would expect this code that needs to change is here: https://github.com/girder/girder/blob/master/girder/utility/s3_assetstore_adapter.py#L369-L408

**Comment by kavehtp** [comment]
Thanks for the pointer. I'm closing this issue.
