### ISSUE TITLE
Downloading slides automatically

### ISSUE THREAD

**Issue by ghadjigeorghiou** [DigitalSlideArchive/HistomicsTK#827]
Hi,

I am developing an app where I would like the user to be able to provide the slide id and for my program to be able to automatically download it for my analysis workflow to run. I cannot work with only the thumbnail of the slide as I am using another library that requires the original slide file. Is there any way to download slides automatically? I tried to use wget with the relevant download link by I cannot authenticate the user successfully. 

Thank you in advance.

Best,
George

**Comment by manthey** [comment]
In our default deployments, we restrict downloads so that they are only permitted to logged in users, even if it is a publicly visible slide.  If this is your own deployment, you can change a setting in the girder configuration file.  Assuming you are using the deployment from digital_slide_archive, this would change:
```
[histomicsui]
# If restrict_downloads is True, only logged-in users can access download and
# tiles/images endpoints.
restrict_downloads = False
```

If this isn't a deployment you manage, or you don't want to circumvent this, you can get an authentication token for a user and pass that as part of your wget or curl command.  If you look at your browser session for the current user, you'll see a `Girder-Token` header.  Add `--header "Girder-Token: <the token>"` to your curl or wget command.

You can get an anonymous session token from the `<server>/api/v1/token/session` endpoint.  That token can be used in lieu of the user token, assuming the file is publicly accessible.
