### ISSUE TITLE
Registration functionality feature

### ISSUE THREAD

**Issue by asmagen** [DigitalSlideArchive/HistomicsTK#832]
Is there a plan to release whole slide registration functionality soon? It is vital for all the projects my institute is dealing with where we have multiplex staining.

Thanks

**Comment by manthey** [comment]
We don't have any timeline in the short term.

There are a couple of approaches to this.  A single affine transform (or probably just rotation and translation) could be used between slides, or, since you often have tissue distortion between slides, you can have use a locally varying transform (though this will change measured lengths and areas).

We made a proof-of-concept demo where a user could mark corresponding points on multiple slides with different staining, then dynamically applied a rotation and translation to produce a good fit at a chosen center (the center of the viewport in the browser in the demo).
