### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by mahtabbigverdi** [DigitalSlideArchive/HistomicsTK#926]
Hi, I get this error after `pip install histomicstk --find-links https://girder.github.io/large_image_wheels` and importing reinhard in Google Colab.
This is the error:
`TypeError: load() missing 1 required positional argument: 'Loader'`

**Comment by manthey** [comment]
Are you just following one of the sample ipython notebooks?  Can you share what you did?

**Comment by mahtabbigverdi** [comment]
yes, I followed this link : https://digitalslidearchive.github.io/HistomicsTK/examples/color_normalization_and_augmentation.html

I commented `import girder_client` but at the first line of importing from the library `(from histomicstk.preprocessing.color_normalization import reinhard
from histomicstk.saliency.tissue_detection import (
    get_slide_thumbnail, get_tissue_mask))` , I got the error

**Comment by manthey** [comment]
Looking in to this, it seems like the current instance of Google colab comes with a slew of packages preinstalled.  Some of these conflict with the ones HistomicsTK specifies.  I was able to actively uninstall a bunch of stuff from colab (including the version of opencv-python, which requires removing its directory), and then install HistomicsTK, and then the imports work as expected.  It will take some effort to track down what the exact conflict in colab.

**Comment by manthey** [comment]
I've made a few changes to how packages are required to work better with Google colab.  Unfortunately, colab in its current incarnation has package conflicts (before one adds any packages via pip) and some packages can't be updated without updating a lot.  The default installation:
```
!pip install histomicstk --find-links https://girder.github.io/large_image_wheels
```
pulls in a newer version of urllib3 than is installed on colab, but that breaks some package on colab.  One way around this is to pin urllib3 to the version that is actually on colab:
```
!pip install urllib3==1.24.3 histomicstk --find-links https://girder.github.io/large_image_wheels
```
(current as of this writing).  This takes a _long_ time for pip to resolve packages because of needing to find a sufficiently ancient version of one of the packages, but installs and works successfully.

colab either should install less or start with fewer packages preimported (or be updated to versions released in the last few years), but I'll leave you to file an issue with colab about that.  I'm closing this, as I don't think there is more that we can do to packages we have control over.
